### ISSUE TITLE
Displays wrong content from select type

### ISSUE THREAD

**Issue by dixonge** [kharissulistiyo/WooCommerce-Custom-Product-Data-Fields#1]
Most field types are working fine, but for 'select' fields the output is the option # instead of the value.

In the WooCommerce product data page, in the Custom Data tab, the product drop-downs are all correct. But when I try to retrieve the value and display it on a WooCommerce template I get the 'option_12' instead of '2003'. Other data field types (text and number) display properly, both in the custom data tab and on the displayed product page.

**Comment by kharissulistiyo** [comment]
> When I try to retrieve the value and display it on a WooCommerce template I get the 'option_12' instead of '2003'.

You can reverse the array value into key. This option outputs the array key. 

Thanks for reporting.

**Comment by dixonge** [comment]
For now I am using this syntax:

`$custom_product_data_fields[] = array(
          'id'          => '_year',
          'type'        => 'select',
          'label'       => __('Year', 'wc_cpdf'),
          'options'     => array(
              '2014'  => __('2014', 'wc_cpdf'),
              '2013'  => __('2013', 'wc_cpdf'),
              '2012'  => __('2012', 'wc_cpdf'),`

**Comment by dixonge** [comment]
This should have been closed six years ago!
